# Generated by Django 2.0.13 on 2021-11-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverSource', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('detailLink', models.CharField(max_length=100)),
            ],
        ),
    ]
